#!/bin/sh
# Bakes the Gemini key from .env into a Swift constant.
#
# The generated file is gitignored. This is the bring-your-own-key model the web
# app already uses, which is fine for a local or TestFlight build — but a key in
# a shipped binary is extractable, so anything public needs a proxy that holds
# the key server-side instead.
set -e

root="$(cd "$(dirname "$0")/../.." && pwd)"
env_file="$root/.env"
out="$root/ios/Skuzic/App/Secrets.swift"

key=""
if [ -f "$env_file" ]; then
    key=$(grep -E '^VITE_GEMINI_API_KEY=' "$env_file" | head -1 | cut -d= -f2- | tr -d '"'"'"' \r\n')
fi

if [ -z "$key" ]; then
    echo "warning: no VITE_GEMINI_API_KEY in $env_file — building without a key" >&2
fi

mkdir -p "$(dirname "$out")"
cat > "$out" <<SWIFT
// Generated by ios/scripts/gen-secrets.sh — do not edit, do not commit.
enum Secrets {
    static let geminiAPIKey = "$key"
}
SWIFT

echo "wrote $out"
